In [1]:
from splinter import Browser
from bs4 import BeautifulSoup
from time import sleep 
import pandas as pd
from selenium import webdriver

In [2]:
top50city_df = pd.read_csv("top50city.csv")
top50city_df

              Location  gaJobs            City State
0         New York, NY     310        New York    NY
1          Chicago, IL     130         Chicago    IL
2    San Francisco, CA     119   San Francisco    CA
3           Austin, TX      81          Austin    TX
4      Los Angeles, CA      80     Los Angeles    CA
5        Charlotte, NC      78       Charlotte    NC
6          Houston, TX      72         Houston    TX
7           Dallas, TX      66          Dallas    TX
8        San Diego, CA      62       San Diego    CA
9     Philadelphia, PA      56    Philadelphia    PA
10          Denver, CO      47          Denver    CO
11     San Antonio, TX      45     San Antonio    TX
12        San Jose, CA      38        San Jose    CA
13         Phoenix, AZ      35         Phoenix    AZ
14     Jersey City, NJ      33     Jersey City    NJ
15           Tempe, AZ      31           Tempe    AZ
16         Seattle, WA      30         Seattle    WA
17        Columbus, OH      29        Columbus    OH
18          Irving, TX      29          Irving    TX
19           Plano, TX      28           Plano    TX
20  Salt Lake City, UT      22  Salt Lake City    UT
21     Santa Clara, CA      22     Santa Clara    CA
22      El Segundo, CA      19      El Segundo    CA
23    Jacksonville, FL      19    Jacksonville    FL
24         Norfolk, VA      18         Norfolk    VA
25       San Mateo, CA      18       San Mateo    CA
26         Burbank, CA      17         Burbank    CA
27    Indianapolis, IN      17    Indianapolis    IN
28      Fort Worth, TX      16      Fort Worth    TX
29       Sunnyvale, CA      16       Sunnyvale    CA
30   Mountain View, CA      15   Mountain View    CA
31      Scottsdale, AZ      15      Scottsdale    AZ
32       Palo Alto, CA      14       Palo Alto    CA
33        Brooklyn, NY      13        Brooklyn    NY
34       Cupertino, CA      13       Cupertino    CA
35         Hampton, VA      13         Hampton    VA
36      Long Beach, CA      13      Long Beach    CA
37    Redwood City, CA      12    Redwood City    CA
38      Menlo Park, CA      11      Menlo Park    CA
39         Oakland, CA      11         Oakland    CA
40         Redmond, WA      11         Redmond    WA
41      Wilmington, DE      11      Wilmington    DE
42      Richardson, TX      10      Richardson    TX
43      Centennial, CO       9      Centennial    CO
44   Downers Grove, IL       9   Downers Grove    IL
45     Foster City, CA       9     Foster City    CA
46    Lake Success, NY       9    Lake Success    NY
47    Santa Monica, CA       9    Santa Monica    CA
48       Arlington, TX       8       Arlington    TX
49        Glendale, CA       8        Glendale    CA

In [3]:
#Splitting dataframe into 3 parts so we do not get banned from scraping from zillow
top17 = top50city_df.iloc[0:18]
top34 = top50city_df.iloc[18:35]
top50 = top50city_df.iloc[35:50]

In [4]:
option = webdriver.ChromeOptions()
option.add_argument("--incognito")

In [5]:
browser = webdriver.Chrome(executable_path='chromedriver.exe', chrome_options=option)

#executable_path = {'executable_path': 'chromedriver.exe'}
#browser = Browser('chrome', **executable_path, headless=False)

C:\Users\Matt\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: use options instead of chrome_options
  """Entry point for launching an IPython kernel.

In [6]:
#city = top50city_df.City
#state = top50city_df.State

In [7]:
base_url = "https://www.zillow.com/homes/"
#https://www.zillow.com/homes/San-Francisco,-CA_rb/
#query_url = f"{base_url}{city},-{state}_rb/"
#query_url

#browser.visit(url)

In [8]:
item_df = pd.DataFrame(columns = ["address", "price", 'info', 'city', 'state'])
print(item_df)

Empty DataFrame
Columns: [address, price, info, city, state]
Index: []

In [9]:
# for x in range(1, 20):
#     sleep(2)

#     html = browser.html
#     soup = BeautifulSoup(html, 'html.parser')

#     quotes = soup.find_all('address', class_='list-card-addr')

#     for quote in quotes:
#         print('page:', x, '-------------')
#         print(quote.text)

#     browser.click_link_by_partial_text('Chevron Right')

In [10]:
# class ZrentItem(object):
#     def __init__(address, price, info, state):
#         self.address = address
#         self.price = price
#         self.info = info
#         self.state = state

In [11]:
#for iterrows - t50_df 
    #create url like  https://www.zillow.com/homes/San-Francisco,-CA_rb/  use city and state column
    #go to browser url
    #indent below
    #update city and state below
    #may have to split up list and add note in code
    #may do incognito

for x in range(0, 1):
    sleep(2)
    
    city = top17.loc[x, 'City']
    state = top17.loc[x, 'State']
    
    query_url = f"{base_url}{city},-{state}_rb/"
    
    browser.visit(query_url)
    
    html = browser.html

    print("%"*29)
    print(type(html))
    soup = BeautifulSoup(html, 'html.parser')

    cardlist = soup.find_all('article', class_='list-card_not-saved')
    print("@"*17)
    print(type(cardlist))
    print(len(cardlist))

    for card in cardlist:
        address = card.find('address', class_='list-card-addr').text
        print("*************7the address is")
        print(address)
        info = card.find('ul', class_='list-card-details').text
        print("*************8the info is")
        print(info)
        try:
            price = card.find('div', class_='list-card-price').text
            
        except:
            print("no price")
            price = ""
        else:
            print("$+" +price)
        
        item_df = item_df.append(pd.DataFrame({'address': [address], 'price': [price], 'info': [info], 'city': [city], 'state': [state]}))
    sleep(5)
    #browser.click_link_by_partial_text('Page 2')

#     for quote in quotes:
#         address = 
#         print('page:', x, '-------------')
#         print(quote.text)

AttributeError: 'WebDriver' object has no attribute 'visit'

In [ ]:
item_df.to_excel('housing.xlsx', sheet_name= 'housing')