In [1]:
from splinter import Browser
from bs4 import BeautifulSoup
from time import sleep 
import pandas as pd
from selenium import webdriver

In [2]:
top50city_df = pd.read_csv("top50city.csv")
top50city_df

              Location  gaJobs            City State
0         New York, NY     310        New York    NY
1          Chicago, IL     130         Chicago    IL
2    San Francisco, CA     119   San Francisco    CA
3           Austin, TX      81          Austin    TX
4      Los Angeles, CA      80     Los Angeles    CA
5        Charlotte, NC      78       Charlotte    NC
6          Houston, TX      72         Houston    TX
7           Dallas, TX      66          Dallas    TX
8        San Diego, CA      62       San Diego    CA
9     Philadelphia, PA      56    Philadelphia    PA
10          Denver, CO      47          Denver    CO
11     San Antonio, TX      45     San Antonio    TX
12        San Jose, CA      38        San Jose    CA
13         Phoenix, AZ      35         Phoenix    AZ
14     Jersey City, NJ      33     Jersey City    NJ
15           Tempe, AZ      31           Tempe    AZ
16         Seattle, WA      30         Seattle    WA
17        Columbus, OH      29        Columbus    OH
18          Irving, TX      29          Irving    TX
19           Plano, TX      28           Plano    TX
20  Salt Lake City, UT      22  Salt Lake City    UT
21     Santa Clara, CA      22     Santa Clara    CA
22      El Segundo, CA      19      El Segundo    CA
23    Jacksonville, FL      19    Jacksonville    FL
24         Norfolk, VA      18         Norfolk    VA
25       San Mateo, CA      18       San Mateo    CA
26         Burbank, CA      17         Burbank    CA
27    Indianapolis, IN      17    Indianapolis    IN
28      Fort Worth, TX      16      Fort Worth    TX
29       Sunnyvale, CA      16       Sunnyvale    CA
30   Mountain View, CA      15   Mountain View    CA
31      Scottsdale, AZ      15      Scottsdale    AZ
32       Palo Alto, CA      14       Palo Alto    CA
33        Brooklyn, NY      13        Brooklyn    NY
34       Cupertino, CA      13       Cupertino    CA
35         Hampton, VA      13         Hampton    VA
36      Long Beach, CA      13      Long Beach    CA
37    Redwood City, CA      12    Redwood City    CA
38      Menlo Park, CA      11      Menlo Park    CA
39         Oakland, CA      11         Oakland    CA
40         Redmond, WA      11         Redmond    WA
41      Wilmington, DE      11      Wilmington    DE
42      Richardson, TX      10      Richardson    TX
43      Centennial, CO       9      Centennial    CO
44   Downers Grove, IL       9   Downers Grove    IL
45     Foster City, CA       9     Foster City    CA
46    Lake Success, NY       9    Lake Success    NY
47    Santa Monica, CA       9    Santa Monica    CA
48       Arlington, TX       8       Arlington    TX
49        Glendale, CA       8        Glendale    CA

In [3]:
#Splitting dataframe into 3 parts so we do not get banned from scraping from zillow
top10 = top50city_df.iloc[0:11]
top20 = top50city_df.iloc[11:21]
top30 = top50city_df.iloc[21:31]
top40 = top50city_df.iloc[31:41]
top50 = top50city_df.iloc[41:50]

In [4]:
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [5]:
base_url = "https://www.zillow.com/homes/"

In [6]:
item_df = pd.DataFrame(columns = ["address", "price", 'info', 'city', 'state'])
print(item_df)

Empty DataFrame
Columns: [address, price, info, city, state]
Index: []

In [ ]:
# for x in range(1, 20):
#     sleep(2)

#     html = browser.html
#     soup = BeautifulSoup(html, 'html.parser')

#     quotes = soup.find_all('address', class_='list-card-addr')

#     for quote in quotes:
#         print('page:', x, '-------------')
#         print(quote.text)

#     browser.click_link_by_partial_text('Chevron Right')

In [ ]:
# class ZrentItem(object):
#     def __init__(address, price, info, state):
#         self.address = address
#         self.price = price
#         self.info = info
#         self.state = state

In [8]:
#for iterrows - t50_df 
    #create url like  https://www.zillow.com/homes/San-Francisco,-CA_rb/  use city and state column
    #go to browser url
    #indent below
    #update city and state below
    #may have to split up list and add note in code
    #may do incognito

for x in range(0, 10):
    sleep(2)
    
    city = top10.loc[x, 'City']
    state = top10.loc[x, 'State']
    
    query_url = f"{base_url}{city},-{state}_rb/"
    
    browser.visit(query_url)
    
    html = browser.html

    print("%"*29)
    print(type(html))
    soup = BeautifulSoup(html, 'html.parser')

    cardlist = soup.find_all('article', class_='list-card_not-saved')
    print("@"*17)
    print(type(cardlist))
    print(len(cardlist))

    for card in cardlist:
        address = card.find('address', class_='list-card-addr').text
        print("*************7the address is")
        print(address)
        info = card.find('ul', class_='list-card-details').text
        print("*************8the info is")
        print(info)
        try:
            price = card.find('div', class_='list-card-price').text
            
        except:
            print("no price")
            price = ""
        else:
            print("$+" +price)
        
        item_df = item_df.append(pd.DataFrame({'address': [address], 'price': [price], 'info': [info], 'city': [city], 'state': [state]}))
    sleep(5)
    #browser.click_link_by_partial_text('Page 2')

#     for quote in quotes:
#         address = 
#         print('page:', x, '-------------')
#         print(quote.text)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
40
*************7the address is
917 N Honore St #1S, Chicago, IL 60622
*************8the info is
3 bds3 ba1,750 sqft
$+$595,000
*************7the address is
10222 S Leavitt St, Chicago, IL 60643
*************8the info is
4 bds3 ba3,200 sqft
$+$635,000
*************7the address is
1133 N Wood St APT 3S, Chicago, IL 60622
*************8the info is
2 bds2 ba1,400 sqft
$+$540,000
*************7the address is
1346 S Wabash Ave UNIT B, Chicago, IL 60605
*************8the info is
2 bds2 ba1,200 sqft
$+$319,000
*************7the address is
3522 W 38th Pl, Chicago, IL 60632
*************8the info is
4 bds2 ba-- sqft
$+$189,900
*************7the address is
50 E 16th St UNIT 1401, Chicago, IL 60616
*************8the info is
2 bds2 ba1,880 sqft
$+$550,000
*************7the address is
4250 N Marine Dr APT 2014, Chicago, IL 60613
*************8the info is
Studio1 ba525 sqft
$+$119,000
*************7the address is
860 W Buckingham Pl APT 2W, Chicago, IL 60657
*************8the info is
3 bds2 ba1,500 sqft
$+$579,500
*************7the address is
8465 W Lawrence Ave APT 2B, Chicago, IL 60656
*************8the info is
2 bds2 ba1,100 sqft
$+$223,000
*************7the address is
336 W Wellington Ave APT 302, Chicago, IL 60657
*************8the info is
2 bds1 ba820 sqft
$+$224,900
*************7the address is
3546 N Panama Ave, Chicago, IL 60634
*************8the info is
2 bds1 ba3,720 sqft
$+$149,900
*************7the address is
3940 W Dickens Ave, Chicago, IL 60647
*************8the info is
3 bds2 ba2,000 sqft
$+$405,000
*************7the address is
5625 N Spaulding Ave APT 2N, Chicago, IL 60659
*************8the info is
3 bds1 ba1,200 sqft
$+$179,900
*************7the address is
8529 S Kingston Ave, Chicago, IL 60617
*************8the info is
3 bds2 ba1,406 sqft
$+$62,999
*************7the address is
2749 W Giddings St APT 3E, Chicago, IL 60625
*************8the info is
2 bds2 ba-- sqft
$+$399,900
*************7the address is
N Wolcott Ave, Chicago, IL 60622
*************8the info is
3 bds3 ba2,000 sqft
$+$825,000
*************7the address is
1122 W Catalpa Ave APT 418, Chicago, IL 60640
*************8the info is
2 bds2 ba-- sqft
$+$255,000
*************7the address is
5056 S Woodlawn Ave #1, Chicago, IL 60615
*************8the info is
5 bds3 ba3,300 sqft
$+$475,000
*************7the address is
3600 N Lake Shore Dr APT 2016, Chicago, IL 60613
*************8the info is
Studio1 ba500 sqft
$+$169,500
*************7the address is
4125 N Kenmore Ave #F, Chicago, IL 60613
*************8the info is
2 bds2 ba-- sqft
$+$360,000
*************7the address is
5108 S Austin Ave, Chicago, IL 60638
*************8the info is
3 bds1 ba2,250 sqft
$+$279,900
*************7the address is
5420 N Sheridan Rd APT 204, Chicago, IL 60640
*************8the info is
2 bds2 ba-- sqft
$+$219,000
*************7the address is
6008 N Landers Ave, Chicago, IL 60646
*************8the info is
3 bds2 ba1,275 sqft
$+$399,900
*************7the address is
6646 W Raven St, Chicago, IL 60631
*************8the info is
4 bds3 ba2,100 sqft
$+$580,000
*************7the address is
3556 W Congress Pkwy, Chicago, IL 60624
*************8the info is
4 bds5 ba-- sqft
$+$329,000
*************7the address is
9345 S Luella Ave, Chicago, IL 60617
*************8the info is
3 bds2 ba836 sqft
$+$167,500
*************7the address is
8729 S Justine St, Chicago, IL 60620
*************8the info is
4 bds2 ba2,000 sqft
$+$169,900
*************7the address is
1920 S Shelby Ct, Chicago, IL 60608
*************8the info is
4 bds4 ba3,000 sqft
$+$949,900
*************7the address is
3461 N Panama Ave, Chicago, IL 60634
*************8the info is
4 bds2 ba1,750 sqft
$+$309,900
*************7the address is
12744 S Sangamon St, Chicago, IL 60643
*************8the info is
3 bds1 ba1,102 sqft
$+$149,999
*************7the address is
5320 N Sheridan Rd APT 510, Chicago, IL 60640
*************8the info is
Studio1 ba865 sqft
$+$139,900
*************7the address is
5230 S University Ave UNIT O, Chicago, IL 60615
*************8the info is
3 bds3 ba1,765 sqft
$+$465,000
*************7the address is
1328 W Elmdale Ave #2E, Chicago, IL 60660
*************8the info is
2 bds2 ba1,700 sqft
$+$389,000
*************7the address is
8017 S Paxton Ave, Chicago, IL 60617
*************8the info is
5 bds3 ba1,400 sqft
$+$315,000
*************7the address is
165 N Field Blvd #C17, Chicago, IL 60601
*************8the info is
-- bds-- ba-- sqft
$+$15,000
*************7the address is
1720 S Michigan Ave APT 3217, Chicago, IL 60616
*************8the info is
1 bd1 ba705 sqft
$+$215,000
*************7the address is
8123 S Manistee Ave, Chicago, IL 60617
*************8the info is
3 bds1 ba1,013 sqft
$+$47,000
*************7the address is
3325 W 37th Pl, Chicago, IL 60632
*************8the info is
5 bds3 ba1,100 sqft
$+$254,999
*************7the address is
440 N Mcclurg Ct APT 1119, Chicago, IL 60611
*************8the info is
1 bd1 ba750 sqft
$+$350,000
*************7the address is
3210 N Kilbourn Ave UNIT 1, Chicago, IL 60641
*************8the info is
3 bds2 ba2,000 sqft
$+$355,000
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
40
*************7the address is
1822 38th Ave, San Francisco, CA 94122
*************8the info is
6 bds3 ba2,401 sqft
$+$1,495,000
*************7the address is
910 Lawton St, San Francisco, CA 94122
*************8the info is
3 bds2 ba2,100 sqft
$+$2,299,000
*************7the address is
715 Mount Vernon Ave, San Francisco, CA 94112
*************8the info is
4 bds1 ba1,075 sqft
$+$1,250,000
*************7the address is
1330 Chestnut St, San Francisco, CA 94123
*************8the info is
3 bds2.5 ba1,765 sqft
$+$1,995,000
*************7the address is
755 Florida St UNIT 2, San Francisco, CA 94110
*************8the info is
1 bd1 ba623 sqft
$+$699,000
*************7the address is
601 Van Ness Ave APT 311, San Francisco, CA 94102
*************8the info is
1 bd1 ba558 sqft
$+$605,000
*************7the address is
260 King St UNIT 553, San Francisco, CA 94107
*************8the info is
1 bd1 ba556 sqft
$+$680,000
*************7the address is
501 Crescent Way APT 5207, San Francisco, CA 94134
*************8the info is
2 bds2 ba1,095 sqft
$+$748,000
*************7the address is
443 Chenery St, San Francisco, CA 94131
*************8the info is
3 bds2 ba1,646 sqft
$+$1,795,000
*************7the address is
Arkansas St, San Francisco, CA 94107
*************8the info is
4 bds3 ba2,150 sqft
$+$2,199,999
*************7the address is
1 Daniel Burnham Ct APT 724, San Francisco, CA 94109
*************8the info is
2 bds2 ba1,131 sqft
$+$999,000
*************7the address is
43-45 Pond St, San Francisco, CA 94114
*************8the info is
2 bds3 ba-- sqft
$+$2,050,000
*************7the address is
522-524 Steiner St, San Francisco, CA 94117
*************8the info is
8 bds5 ba4,376 sqft
$+$2,595,000
*************7the address is
1479 Revere Ave #1481, San Francisco, CA 94124
*************8the info is
Studio-- ba-- sqft
$+$1,100,000
*************7the address is
1243 Quesada Ave, San Francisco, CA 94124
*************8the info is
3 bds1 ba1,250 sqft
$+$850,000
*************7the address is
209 Prentiss St, San Francisco, CA 94110
*************8the info is
3 bds2.5 ba-- sqft
$+$1,975,000
*************7the address is
Address Not Disclosed, San Francisco, CA 94103
*************8the info is
Studio-- ba4,185 sqft
$+$2,495,000
*************7the address is
333 1st St UNIT 1602, San Francisco, CA 94105
*************8the info is
1 bd1 ba713 sqft
$+$949,000
*************7the address is
1623 18th St, San Francisco, CA 94107
*************8the info is
2 bds2 ba1,102 sqft
$+$1,200,000
*************7the address is
280 Spear Street #32D Plan, MIRA
*************8the info is
2 bds2 ba1,100 sqft
$+$1,995,000+
*************7the address is
614 Hamilton St, San Francisco, CA 94134
*************8the info is
3 bds2 ba1,036 sqft
$+$1,195,000
*************7the address is
420 Hazelwood Ave, San Francisco, CA 94127
*************8the info is
4 bds3 ba2,939 sqft
$+$2,495,000
*************7the address is
5320 Diamond Heights Blvd APT 305K, San Francisco, CA 94131
*************8the info is
1 bd1 ba657 sqft
$+$700,000
*************7the address is
135 Alhambra St, San Francisco, CA 94123
*************8the info is
3 bds3.5 ba2,288 sqft
$+$2,695,000
*************7the address is
479-481 20th Ave, San Francisco, CA 94121
*************8the info is
4 bds2 ba2,560 sqft
$+$1,995,000
*************7the address is
950 Harrison St UNIT 101, San Francisco, CA 94107
*************8the info is
3 bds2 ba1,642 sqft
$+$1,395,000
*************7the address is
1370 11th Ave, San Francisco, CA 94122
*************8the info is
Studio-- ba4,380 sqft
$+$2,600,000
*************7the address is
1775 Oak St, San Francisco, CA 94117
*************8the info is
2 bds1 ba1,707 sqft
$+$1,300,000
*************7the address is
3550 Baker St, San Francisco, CA 94123
*************8the info is
4 bds3.5 ba3,586 sqft
$+$4,995,000
*************7the address is
65 Carver St, San Francisco, CA 94110
*************8the info is
3 bds2 ba980 sqft
$+$1,395,000
*************7the address is
2 Mint Plz SUITE 1002, San Francisco, CA 94103
*************8the info is
1 bd1 ba1,199 sqft
$+$1,495,000
*************7the address is
66 Cleary Ct APT 605, San Francisco, CA 94109
*************8the info is
3 bds2 ba1,316 sqft
$+$1,285,000
*************7the address is
71 Sanchez St APT C, San Francisco, CA 94114
*************8the info is
1 bd1 ba768 sqft
$+$980,000
*************7the address is
33 Midway St APT 302, San Francisco, CA 94133
*************8the info is
2 bds1.5 ba854 sqft
$+$949,000
*************7the address is
2912 Sacramento St, San Francisco, CA 94115
*************8the info is
4 bds3 ba2,500 sqft
$+$4,295,000
*************7the address is
223 Evelyn Way, San Francisco, CA 94127
*************8the info is
3 bds2 ba1,622 sqft
$+$1,465,000
*************7the address is
1450 Franklin St #505, San Francisco, CA 94109
*************8the info is
2 bds2 ba1,326 sqft
$+$1,699,000
*************7the address is
1623 Page St, San Francisco, CA 94117
*************8the info is
4 bds2.5 ba2,180 sqft
$+$1,825,000
*************7the address is
1895 Pacific Ave APT 406, San Francisco, CA 94109
*************8the info is
1 bd1 ba1,165 sqft
$+$1,149,000
*************7the address is
85 Cleary Ct APT 4, San Francisco, CA 94109
*************8the info is
3 bds2 ba1,395 sqft
$+$899,000

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
40
*************7the address is
501 West Ave #1602, Austin, TX 78701
*************8the info is
1 bd2 ba846 sqft
$+$675,000
*************7the address is
1104 Marcy St #D, Austin, TX 78745
*************8the info is
2 bds2 ba1,096 sqft
$+$469,900
*************7the address is
2103 Charlotte Estates Dr, Austin, TX 78744
*************8the info is
4 bds2 ba1,611 sqft
$+$280,000
*************7the address is
1104 Marcy St #C, Austin, TX 78745
*************8the info is
4 bds4 ba2,144 sqft
$+$755,000
*************7the address is
5801 Ann Jene Ct, Austin, TX 78744
*************8the info is
3 bds2 ba1,752 sqft
$+$289,900
*************7the address is
2603 Rogge Ln, Austin, TX 78723
*************8the info is
4 bds2 ba2,408 sqft
$+$589,990
*************7the address is
300 Bowie St APT 3303, Austin, TX 78703
*************8the info is
2 bds2 ba1,061 sqft
$+$760,000
*************7the address is
10322 Wolftrap Dr, Austin, TX 78749
*************8the info is
4 bds3 ba3,515 sqft
$+$529,000
*************7the address is
8005 Siringo Pass, Austin, TX 78749
*************8the info is
3 bds3 ba2,328 sqft
$+$465,000
*************7the address is
4110 Ridgeline Trl, Austin, TX 78731
*************8the info is
3 bds3 ba1,947 sqft
$+$390,000
*************7the address is
B2-A Plan, Little Ford South Congress
*************8the info is
2 bds2 ba1,111 sqft
$+$418,800+
*************7the address is
(undisclosed Address), Austin, TX 78748
*************8the info is
3 bds3 ba1,436 sqft
$+$290,500
*************7the address is
2013 West Loop, Austin, TX 78758
*************8the info is
Studio-- ba4,124 sqft
$+$615,000
*************7the address is
6024 Signal Point, Austin, TX 78724
*************8the info is
3 bds2 ba1,320 sqft
$+$229,000
*************7the address is
9709 Mcknight Loop UNIT 32, Austin, TX 78717
*************8the info is
3 bds3 ba2,611 sqft
$+$499,000
*************7the address is
Sandpiper Plan, Loyola
*************8the info is
2 bds2 ba1,531 sqft
$+$418,990+
*************7the address is
2405 Tower Dr, Austin, TX 78703
*************8the info is
5 bds6 ba4,306 sqft
$+$1,999,900
*************7the address is
13100 New Boston Bnd, Austin, TX 78729
*************8the info is
4 bds3 ba2,259 sqft
$+$479,900
*************7the address is
3203 E 16th St, Austin, TX 78721
*************8the info is
2 bds1 ba728 sqft
$+$325,000
*************7the address is
2402 Santa Rita St, Austin, TX 78702
*************8the info is
2 bds1 ba576 sqft
$+$365,000
*************7the address is
Marion Plan, Bradshaw Crossing   Ridgepointe and Cottage Collection
*************8the info is
3 bds2 ba1,449 sqft
$+$275,990+
*************7the address is
10613 Chestnut Ridge Rd, Austin, TX 78726
*************8the info is
5 bds4 ba4,074 sqft
$+$649,000
*************7the address is
2615 Zaragosa St, Austin, TX 78702
*************8the info is
Studio-- ba2,991 sqft
$+$775,000
*************7the address is
6405 Middleham Pl, Austin, TX 78745
*************8the info is
4 bds3 ba1,618 sqft
$+$425,000
*************7the address is
7207 Bassett Ct, Austin, TX 78741
*************8the info is
3 bds4 ba2,033 sqft
$+$399,900
*************7the address is
8915 N Georgian Dr, Austin, TX 78753
*************8the info is
5 bds3 ba1,670 sqft
$+$315,900
*************7the address is
5725 Fort Benton Dr, Austin, TX 78735
*************8the info is
4 bds4 ba3,124 sqft
$+$799,900
*************7the address is
2020 S Congress Ave APT 1120, Austin, TX 78704
*************8the info is
1 bd1 ba403 sqft
$+$185,000
*************7the address is
3101 Govalle Ave #104, Austin, TX 78702
*************8the info is
1 bd1 ba1,040 sqft
$+$384,000
*************7the address is
The Justin Plan, Tiermo
*************8the info is
4 bds2 ba1,832 sqft
$+$257,990+
*************7the address is
2002 Payne Ave, Austin, TX 78757
*************8the info is
7,056 sqft lot
$+$495,000
*************7the address is
8204 Peaceful Hill Ln, Austin, TX 78748
*************8the info is
3 bds2 ba1,083 sqft
$+$335,000
*************7the address is
2604 W 48th St, Austin, TX 78731
*************8the info is
4 bds2 ba2,713 sqft
$+$899,000
*************7the address is
1116 Winifred Dr, Austin, TX 78748
*************8the info is
4 bds3 ba1,997 sqft
$+$379,990
*************7the address is
1216 Winnie Dr, Austin, TX 78748
*************8the info is
4 bds3 ba2,030 sqft
$+$381,740
*************7the address is
1117 Winifred Dr, Austin, TX 78748
*************8the info is
4 bds4 ba2,152 sqft
$+$382,090
*************7the address is
10021 Wild Dunes Dr, Austin, TX 78747
*************8the info is
0.69 acres lot
$+$100,000
*************7the address is
8808 Cattle Baron Path, Austin, TX 78747
*************8the info is
4 bds3 ba2,788 sqft
$+$415,000
*************7the address is
5700 Westslope Dr, Austin, TX 78731
*************8the info is
4 bds3 ba2,486 sqft
$+$839,900
*************7the address is
1529 Barton Springs Rd APT 25, Austin, TX 78704
*************8the info is
2 bds3 ba1,984 sqft
$+$675,000
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
40
*************7the address is
5330 Yarmouth Ave UNIT 216, Los Angeles, CA 91316
*************8the info is
2 bds2 ba1,765 sqft
$+$540,000
*************7the address is
915 Hawaiian Ave, Wilmington, CA 90744
*************8the info is
5 bds2 ba1,939 sqft
$+$625,000
*************7the address is
1332 Westerly Ter, Los Angeles, CA 90026
*************8the info is
4 bds2 ba1,800 sqft
$+$2,600,000
*************7the address is
9924 Wealtha Ave, Sun Valley, CA 91352
*************8the info is
3 bds2 ba1,498 sqft
$+$689,000
*************7the address is
18954 Sherman Way UNIT 8, Los Angeles, CA 91335
*************8the info is
2 bds3 ba1,095 sqft
$+$360,000
*************7the address is
8301 Wiley Post Ave, Los Angeles, CA 90045
*************8the info is
2 bds2 ba1,196 sqft
$+$619,000
*************7the address is
13540 Bayliss Rd, Los Angeles, CA 90049
*************8the info is
3 bds3 ba2,613 sqft
$+$2,500,000
*************7the address is
18555 Collins St APT C18, Los Angeles, CA 91356
*************8the info is
2 bds2 ba955 sqft
$+$360,000
*************7the address is
3132 Garden Ave, Los Angeles, CA 90039
*************8the info is
4 bds4 ba2,164 sqft
$+$1,600,000
*************7the address is
1425 N Detroit St APT 204, Los Angeles, CA 90046
*************8the info is
3 bds2 ba1,420 sqft
$+$777,000
*************7the address is
6174 Mulholland Hwy, Los Angeles, CA 90068
*************8the info is
3 bds3 ba2,500 sqft
$+$1,699,000
*************7the address is
3115 S Kerckhoff Ave, San Pedro, CA 90731
*************8the info is
3 bds2 ba1,012 sqft
$+$610,000
*************7the address is
1425 Lomita Blvd UNIT 2, Harbor City, CA 90710
*************8the info is
3 bds3 ba1,456 sqft
$+$575,000
*************7the address is
5050 Irvington Pl, Los Angeles, CA 90042
*************8the info is
2 bds2 ba1,032 sqft
$+$700,000
*************7the address is
11150 Glenoaks Blvd UNIT 44, Los Angeles, CA 91331
*************8the info is
2 bds2 ba1,017 sqft
$+$319,900
*************7the address is
1735 S Hobart Blvd, Los Angeles, CA 90006
*************8the info is
4 bds2 ba1,822 sqft
$+$929,000
*************7the address is
5401 Red Oak Dr, Los Angeles, CA 90068
*************8the info is
4 bds4 ba2,506 sqft
$+$2,899,000
*************7the address is
5454 Zelzah Ave APT 209, Los Angeles, CA 91316
*************8the info is
2 bds2 ba1,234 sqft
$+$435,000
*************7the address is
8901 Eton Ave #82, Canoga Park, CA 91304
*************8the info is
2 bds2 ba1,440 sqft
$+$130,000
*************7the address is
2331 S Cloverdale Ave, Los Angeles, CA 90016
*************8the info is
3 bds3 ba1,867 sqft
$+$985,000
*************7the address is
3171 W 11th St, Los Angeles, CA 90006
*************8the info is
2 bds2 ba2,044 sqft
$+$1,499,000
*************7the address is
5429 Newcastle Ave APT 203, Los Angeles, CA 91316
*************8the info is
1 bd1 ba726 sqft
$+$290,000
*************7the address is
4548 Farmdale Ave, North Hollywood, CA 91602
*************8the info is
3 bds2 ba1,740 sqft
$+$1,395,000
*************7the address is
19606 Vintage St, Northridge, CA 91324
*************8the info is
4 bds3 ba2,453 sqft
$+$945,000
*************7the address is
12682 Millennium, Playa Vista, CA 90094
*************8the info is
4 bds4 ba3,148 sqft
$+$2,688,888
*************7the address is
10807 Paso Robles Ave, Granada Hills, CA 91344
*************8the info is
3 bds2 ba1,332 sqft
$+$639,000
*************7the address is
1504 Paseo De Oro, Pacific Palisades, CA 90272
*************8the info is
4 bds4 ba2,952 sqft
$+$2,159,000
*************7the address is
16033 Vose St, Van Nuys, CA 91406
*************8the info is
4 bds2 ba2,858 sqft
$+$1,095,000
*************7the address is
7044 Los Tilos Rd, Los Angeles, CA 90068
*************8the info is
4 bds4 ba4,446 sqft
$+$4,750,000
*************7the address is
Kingsbury St, Los Angeles, CA 91344
*************8the info is
2 bds2 ba1,218 sqft
$+$399,000
*************7the address is
1234 Wilshire Blvd APT 224, Los Angeles, CA 90017
*************8the info is
2 bds2 ba1,030 sqft
$+$650,000
*************7the address is
20 Ironsides St APT 16, Marina Del Rey, CA 90292
*************8the info is
2 bds3 ba1,875 sqft
$+$1,647,000
*************7the address is
5210 Premiere Hills Cir APT 120, Woodland Hills, CA 91364
*************8the info is
1 bd1 ba788 sqft
$+$459,900
*************7the address is
9210 Van Nuys Blvd UNIT 22, Los Angeles, CA 91402
*************8the info is
2 bds2 ba1,006 sqft
$+$315,000
*************7the address is
13956 Wyandotte St, Van Nuys, CA 91405
*************8the info is
3 bds2 ba1,436 sqft
$+$659,000
*************7the address is
904 W 62nd St, Los Angeles, CA 90044
*************8the info is
5 bds3 ba1,628 sqft
$+$720,000
*************7the address is
5326 Cronus St, Los Angeles, CA 90032
*************8the info is
6 bds3 ba2,693 sqft
$+$839,000
*************7the address is
A2 Plan, Coolidge Place
*************8the info is
2 bds2 ba1,590 sqft
$+$869,495+
*************7the address is
Isabel St, Los Angeles, CA 90065
*************8the info is
3 bds2 ba720 sqft
$+$729,999
*************7the address is
1523 S Leland St, San Pedro, CA 90731
*************8the info is
3 bds2 ba1,316 sqft
$+$699,900

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
40
*************7the address is
1701 Pine Mountain Rd, Charlotte, NC 28214
*************8the info is
3 bds3 ba2,038 sqft
$+$225,000
*************7the address is
6107 Glendock Ct, Charlotte, NC 28269
*************8the info is
3 bds3 ba1,703 sqft
$+$267,900
*************7the address is
6551 Point Comfort Ln, Charlotte, NC 28226
*************8the info is
1 bd2 ba809 sqft
$+$130,000
*************7the address is
315 Arlington Ave UNIT 1802, Charlotte, NC 28203
*************8the info is
1 bd1 ba720 sqft
$+$349,500
*************7the address is
4614 Brooktree Dr, Charlotte, NC 28208
*************8the info is
4 bds2 ba1,712 sqft
$+$197,000
*************7the address is
6133 Hailstone Rd, Charlotte, NC 28215
*************8the info is
3 bds3 ba1,887 sqft
$+$276,935
*************7the address is
3130 Walnut Park Dr, Charlotte, NC 28262
*************8the info is
2 bds2 ba1,047 sqft
$+$140,000
*************7the address is
1931 Ferncliff Rd, Charlotte, NC 28211
*************8the info is
5 bds6 ba5,504 sqft
$+$3,000,000
*************7the address is
8049 Stoneham Ct, Matthews, NC 28105
*************8the info is
3 bds3 ba1,404 sqft
$+$172,000
*************7the address is
London Plan, Reserve at North Reach
*************8the info is
4 bds3 ba3,237 sqft
$+$384,990+
*************7the address is
1534 Rumstone Ln, Charlotte, NC 28262
*************8the info is
3 bds3 ba1,722 sqft
$+$220,000
*************7the address is
202 Minitree Ln, Charlotte, NC 28214
*************8the info is
3 bds3 ba2,144 sqft
$+$242,000
*************7the address is
8125 Kings Creek Dr, Charlotte, NC 28273
*************8the info is
3 bds3 ba1,543 sqft
$+$169,500
*************7the address is
Aden Plan, City Park - The Heights Series
*************8the info is
4 bds4 ba2,124 sqft
$+$319,990+
*************7the address is
Conrad TM Plan, North Reach
*************8the info is
3 bds2 ba2,450 sqft
$+$335,990+
*************7the address is
13116 Palisades Shoals Rd, Uninc, NC 28278
*************8the info is
3 bds3 ba2,730 sqft
$+$575,000
*************7the address is
Lily Plan, Dillon Lakes
*************8the info is
4 bds3 ba1,900 sqft
$+$264,990+
*************7the address is
7111 Founders Club Ct #6, Charlotte, NC 28269
*************8the info is
3 bds3 ba1,544 sqft
$+$199,990
*************7the address is
14906 Brotherly Ln, Charlotte, NC 28278
*************8the info is
3 bds2 ba1,895 sqft
$+$274,900
*************7the address is
6931 Meridale Forest Dr #100, Charlotte, NC 28269
*************8the info is
4 bds3 ba2,230 sqft
$+$350,120
*************7the address is
7006 Meridale Forest Dr, Charlotte, NC 28269
*************8the info is
4 bds3 ba2,432 sqft
$+$366,636
*************7the address is
7002 Meridale Forest Dr, Charlotte, NC 28269
*************8the info is
5 bds4 ba3,222 sqft
$+$388,408
*************7the address is
Bradley Plan, Synergy at Midwood
*************8the info is
2 bds3 ba1,389 sqft
$+$399,443+
*************7the address is
911 Cityscape Dr, Charlotte, NC 28205
*************8the info is
3 bds4 ba1,876 sqft
$+$545,000
*************7the address is
6507 Old Post Rd, Charlotte, NC 28212
*************8the info is
3 bds2 ba1,741 sqft
$+$300,000
*************7the address is
1305 N Caldwell St, Charlotte, NC 28206
*************8the info is
3 bds1 ba1,056 sqft
$+$399,999
*************7the address is
2603 Bridle Brook Way #4, Charlotte, NC 28270
*************8the info is
4 bds4 ba3,100 sqft
$+$524,900
*************7the address is
8338 Rudolph Rd, Charlotte, NC 28216
*************8the info is
2 bds2 ba1,050 sqft
$+$150,000
*************7the address is
514 W 10th St UNIT 401, Charlotte, NC 28202
*************8the info is
1 bd1 ba526 sqft
$+$150,000
*************7the address is
7643 Briardale Dr, Charlotte, NC 28212
*************8the info is
3 bds2 ba2,093 sqft
$+$295,000
*************7the address is
17010 Harcombe Dr, Charlotte, NC 28277
*************8the info is
5 bds5 ba4,610 sqft
$+$700,000
*************7the address is
13931 Canterbury Castle Dr, Charlotte, NC 28273
*************8the info is
2 bds2 ba1,440 sqft
$+$292,454
*************7the address is
Lansing Plan, The Woods at Davis Lake
*************8the info is
3 bds3 ba1,699 sqft
$+$247,990+
*************7the address is
6129 Hailstone Rd, Charlotte, NC 28215
*************8the info is
3 bds3 ba1,658 sqft
$+$270,900
*************7the address is
6136 Hailstone Rd, Charlotte, NC 28215
*************8the info is
3 bds3 ba1,887 sqft
$+$286,900
*************7the address is
1704 Sugar Hollow Dr, Charlotte, NC 28214
*************8the info is
3 bds3 ba1,569 sqft
$+$235,000
*************7the address is
10920 Chalkbark Ln #B23-92, Charlotte, NC 28262
*************8the info is
3 bds3 ba1,766 sqft
$+$298,289
*************7the address is
209 Brooklain Dr, Charlotte, NC 28214
*************8the info is
3 bds2 ba1,939 sqft
$+$269,900
*************7the address is
4923 Park Rd APT C, Charlotte, NC 28209
*************8the info is
2 bds2 ba821 sqft
$+$188,000
*************7the address is
612 Bennington Pl, Charlotte, NC 28211
*************8the info is
4 bds4 ba3,078 sqft
$+$625,000
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<class 'str'>
@@@@@@@@@@@@@@@@@
<class 'bs4.element.ResultSet'>
0